# KNN Classification of Wheat Seed Varieties

In [47]:
# Import Necessary Libaries

import numpy as np 
import pandas as pd
from sklearn.model_selection import train_test_split
from collections import Counter

In [48]:
# Load seed Dataset

column_name = [
    "Area", "Perimeter", "Compactness", "KernelLength", "KernelWidth", "AsymmetryCoeff", "GrooveLength", "Class"
]

data = pd.read_csv("seeds_dataset.txt", delim_whitespace = True, names= column_name)
data.head()

C:\Users\C5144878\AppData\Local\Temp\ipykernel_17576\1436851818.py:7: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  data = pd.read_csv("seeds_dataset.txt", delim_whitespace = True, names= column_name)

,Area,Perimeter,Compactness,KernelLength,KernelWidth,AsymmetryCoeff,GrooveLength,Class
0,15.26,14.84,0.8710,5.763,3.312,2.221,5.220,1
1,14.88,14.57,0.8811,5.554,3.333,1.018,4.956,1
2,14.29,14.09,0.9050,5.291,3.337,2.699,4.825,1
3,13.84,13.94,0.8955,5.324,3.379,2.259,4.805,1
4,16.14,14.99,0.9034,5.658,3.562,1.355,5.175,1

In [49]:
# Preparing Features and Labels

X = data.drop("Class", axis = 1)
y = data['Class']

In [50]:
X.head()

,Area,Perimeter,Compactness,KernelLength,KernelWidth,AsymmetryCoeff,GrooveLength
0,15.26,14.84,0.8710,5.763,3.312,2.221,5.220
1,14.88,14.57,0.8811,5.554,3.333,1.018,4.956
2,14.29,14.09,0.9050,5.291,3.337,2.699,4.825
3,13.84,13.94,0.8955,5.324,3.379,2.259,4.805
4,16.14,14.99,0.9034,5.658,3.562,1.355,5.175

In [51]:
# Split into training and test sets

X_train,X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state =1)

In [52]:
X_train.shape,y_train.shape

((168, 7), (168,))

In [53]:
X_test.shape,y_test.shape

((42, 7), (42,))

In [54]:
# Define Euclidean Distance function

def euclidean_distance(x1,x2):
    return np.sqrt(np.sum((x1-x2)**2))

In [55]:
# Define KNN Classifier from Scratch

class KNN:
    def __init__(self, k=3):
        self.k =k

    def fit(self, X, y):
        self.X_train = np.array(X)
        self.y_train = np.array(y)
    
    def predict(self, X):
        X = np.array(X)
        return np.array([self._predict(x) for x in X])

    def _predict(self, x):
        # Calculate distance between x and all training samples
        distances = [euclidean_distance(x, x_train) for x_train in self.X_train]
    
        # Find the indices of k smallest distances
        k_indices = np.argsort(distances)[:self.k]
    
        # Collect the labels of the k nearest neighbours
        k_nearest_labels = [self.y_train[i] for i in k_indices]
    
        # Majority vote
        most_common = Counter(k_nearest_labels).most_common(1)
    
        return most_common[0][0]

In [56]:
# Initialize model train and predict

knn = KNN(k=5)
knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)

#Evaluate model accuracy
accuracy = np.mean(y_pred==y_test)
print(f"Accuracy of Seeds Dataset: {accuracy:.2f}")

Accuracy of Seeds Dataset: 0.86