# Predicting Titanic Survival Using Naive Bayes

## A Machine Learning Approach to Disaster Analysis

In [4]:
#Import required library

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.impute import SimpleImputer #To Handle missing Values

In [5]:
#Load the Titanic Dataset
df = pd.read_csv("titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [8]:
# Select and prepare features

df_model = df[["Survived", "Pclass", "Sex", "Age", "Fare"]]
df_model["Sex"] = df_model["Sex"].map({"male":0, "female":1})

C:\Users\C5144878\AppData\Local\Temp\ipykernel_5344\2429501290.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model["Sex"] = df_model["Sex"].map({"male":0, "female":1})

In [9]:
df_model.head()

   Survived  Pclass  Sex   Age     Fare
0         0       3    0  22.0   7.2500
1         1       1    1  38.0  71.2833
2         1       3    1  26.0   7.9250
3         1       1    1  35.0  53.1000
4         0       3    0  35.0   8.0500

In [11]:
df_model.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
Fare          0
dtype: int64

In [12]:
# Handle missing values (Impute Age)

X = df_model.drop("Survived", axis =1)
y = df_model["Survived"]

#Use SimpleImputer to fill missing Age with Mean

imputer = SimpleImputer(strategy = "mean") #Mean imputation for numerical columns
X_imputed = imputer.fit_transform(X)

In [13]:
X.head()

   Pclass  Sex   Age     Fare
0       3    0  22.0   7.2500
1       1    1  38.0  71.2833
2       3    1  26.0   7.9250
3       1    1  35.0  53.1000
4       3    0  35.0   8.0500

In [14]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [15]:
#Now X_imputed is a NumPy array with no missing values

import numpy as np
np.isnan(X_imputed).any()

np.False_

In [16]:
#Split into Train and Tests sets

X_train,X_test,y_train,y_test = train_test_split(X_imputed, y, test_size = 0.2, random_state = 42)

In [17]:
X_train.shape, y_train.shape

((712, 4), (712,))

In [18]:
X_test.shape, y_test.shape

((179, 4), (179,))

In [19]:
# Train Naive Bayes Classifier

nb_model = GaussianNB()

nb_model.fit(X_train,y_train)

GaussianNB()

In [20]:
# Make Prediction and Evaluate

y_pred = nb_model.predict(X_test)

#Evaluation Metrics
print("Acuracy:", accuracy_score(y_test,y_pred))
print("\n Confusion Matrix:\n", confusion_matrix(y_test,y_pred))
print("\n Classification Report:\n", classification_report(y_test,y_pred))

Acuracy: 0.7597765363128491

 Confusion Matrix:
 [[83 22]
 [21 53]]

 Classification Report:
               precision    recall  f1-score   support

           0       0.80      0.79      0.79       105
           1       0.71      0.72      0.71        74

    accuracy                           0.76       179
   macro avg       0.75      0.75      0.75       179
weighted avg       0.76      0.76      0.76       179

In [21]:
# Summary

# 📢 "Out of 179 total predictions, around 76% were correct.

# That's a decent accuracy, especially for a simple probabilistic model like Naive Bayes."

# Fairly balanced performance across both classes

# Some room for improvement, especially in distinguishing class 1