# Python Implementation of TD-IDF(Term Frequency - Inverse Document Frequency)

**Step 1: Import necessary libraries**

In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

**Step 2: Define a small corpus(3 documents)**

In [2]:
docs = [
    "Cancer is a deadly disease",
    "Cancer treatment is expensive",
    "Regular excercise prevents disease"
]

**Step 3: Initialize TD-IDF Vectorizer**

In [4]:
vectorizer = TfidfVectorizer()

**Step 4: Fit and transform the text**

In [5]:
X = vectorizer.fit_transform(docs)

**Step 5: Convert to DataFrame for better readability**

In [6]:
df = pd.DataFrame(X.toarray(), columns = vectorizer.get_feature_names_out())

In [7]:
df

,cancer,deadly,disease,excercise,expensive,is,prevents,regular,treatment
0,0.459854,0.604652,0.459854,0.000000,0.000000,0.459854,0.000000,0.000000,0.000000
1,0.428046,0.000000,0.000000,0.000000,0.562829,0.428046,0.000000,0.000000,0.562829
2,0.000000,0.000000,0.402040,0.528635,0.000000,0.000000,0.528635,0.528635,0.000000

**Step 6: Display TF-IDF Values**

In [9]:
df.round(2)

,cancer,deadly,disease,excercise,expensive,is,prevents,regular,treatment
0,0.46,0.6,0.46,0.00,0.00,0.46,0.00,0.00,0.00
1,0.43,0.0,0.00,0.00,0.56,0.43,0.00,0.00,0.56
2,0.00,0.0,0.40,0.53,0.00,0.00,0.53,0.53,0.00

---

##  What You Can Observe

Words like "cancer" appear in multiple documents

* Even though "cancer" is an important word, its IDF is lower because it's not rare across the corpus.
* This results in a moderate TF-IDF score.

Words like "deadly", "expensive", and "prevents" appear only once

* These are unique to individual documents — making them highly specific.
* Their IDF is high, so even with a low TF, the TF-IDF score is high.